#define GROWTH_RATE 0.15f
#define TURN_SPEED 8.0f
#define MOVE_RATE 2.0f
#define FARM_WIDTH 4
#define WOODS_WIDTH 6
#define FARM_TILE_WIDTH 2.0f
#define TIME_TO_PLOUGH 0.2f
#define RETURN_TO_UNPLOUGHED_PROBABILITY 1.0f
