#define GROWTH_RATE 0.15f
#define TURN_SPEED 8.0f
#define MOVE_RATE 2.0f
#define FARM_WIDTH 4
#define WOODS_WIDTH 6
#define FARM_TILE_WIDTH 2.0f
#define TIME_TO_PLOUGH 0.2f
#define RETURN_TO_UNPLOUGHED_PROBABILITY 1.0f
#define SPADE_RETURN_TO_UNPLOUGHED_PROBABILITY 0.5f
#define SHOP_WIDTH 3
enum ITEM_IDS {
	ITEM_MONEYSEED,
	ITEM_SPADE,
	ITEM_OWLSEED,
	ITEM_OWL,
};
#define CHEST_REWARD 12
#define OWL_COST 30
#define MONEY_COST 10
#define MONEY_PLANT_CASH 15
#define SPADE_COST 15
